name: "Conventional Commits Enforcer"
description: "Enforces conventional commit format on PR titles for squash merges to protected branches"
author: "Kyle Bowden"
branding:
  icon: "git-commit"
  color: "blue"

inputs:
  token:
    description: "GitHub token for API access"
    required: true
    default: "${{ github.token }}"

  target-branch:
    description: "Target branch to protect (default: main)"
    required: false
    default: "main"

  allowed-types:
    description: "Comma-separated list of allowed commit types"
    required: false
    default: "feat,fix,docs,style,refactor,perf,test,build,ci,chore,revert"

  strict-mode:
    description: "Enable strict mode for more rigorous validation"
    required: false
    default: "false"

  comment-on-success:
    description: "Comment on PR even when validation passes"
    required: false
    default: "false"

outputs:
  valid:
    description: "Whether all commits are valid"
  invalid-commits:
    description: "JSON array of invalid commits"
  total-commits:
    description: "Total number of commits checked"

runs:
  using: "node20"
  main: "dist/index.js"

permissions:
  contents: read
  pull-requests: write
  actions: read
